import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import contactRouter from './routes/contact.js';
const app = express();
const port = Number(process.env.PORT ?? 4000);
app.use(cors({ origin: process.env.CLIENT_ORIGIN ?? 'http://localhost:5173' }));
app.use(express.json());
app.get('/api/health', (_req, res) => res.json({ ok: true, service: 'lawyer-demo-api' }));
app.use('/api/contact', contactRouter);
app.listen(port, () => console.log(`API running on http://localhost:${port}`));
